### ISSUE TITLE
Do you accept contributions?

### ISSUE THREAD

**Issue by leinardi** [deater/test_proc#2]
Hi, do you accept contribution to this project? 

Can I make a PR for these CPUs?

1. Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
2. Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
3. Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz

**Comment by deater** [comment]
feel free to submit PRs, or if it's easier you can just e-mail the cpuinfo files to me and I'll make sure they get applied

**Comment by leinardi** [comment]
I prefer using PR :)

#4
